[package]
name        = "qvnt"
version     = "0.1.0"
authors     = ["Denis Drozhzhin <denisdrozhzhin1999@gmail.com>"]
edition     = "2018"
repository  = "https://github.com/MucTepDayH16/qvnt.git"
readme      = "README.md"
description = "Quantum Simulation"

[[bench]]
name        = "criterion"
harness     = false

[dependencies]
criterion   = "0.3"
num         = "0.4"
float-cmp   = "0.8"
rand        = "0.8"
rand_distr  = "0.4"
rayon       = "1.5"