[package]
name        = "qvnt"
version     = "0.3.1"
authors     = ["Denis Drozhzhin <denisdrozhzhin1999@gmail.com>"]
edition     = "2018"
repository  = "https://github.com/MucTepDayH16/qvnt/"
readme      = "README.md"
description = "Advanced quantum computation simulator."
license     = "MIT OR Apache-2.0"

[dependencies]
num-complex = "0.4"
float-cmp   = "0.8"
rand        = "0.8"
rand_distr  = "0.4"
rayon       = "1.5"
rustyline   = "9.0"
clap        = "2.33"
qasm        = { version = "*", path = "./qasm-rust" }

[[bin]]
name = "qvnt-i"
test = true
bench = false