[package]
name        = "qvnt"
version     = "0.3.2"
description = "Advanced quantum computation simulator."
keywords    = ["quantum", "theoretical", ]
categories  = ["concurrency", "simulation", "mathematics", "science", ]

authors     = ["Denis Drozhzhin <denisdrozhzhin1999@gmail.com>"]
edition     = "2018"
repository  = "https://github.com/MucTepDayH16/qvnt/"
readme      = "README.md"
license-file = "LICENSE.md"

[dependencies]
criterion   = "0.3"
lazy_static = "1.4"
num-complex = "0.4"
float-cmp   = "0.8"
rand        = "0.8"
rand_distr  = "0.4"
rayon       = "1.5"

[[bench]]
name        = "performance"
harness     = false
