[package]
name        = "qvnt"
version     = "0.3.2"
description = "Advanced quantum computation simulator."
keywords    = ["theoretical", "quantum-computing", "quantum-simulator", "quantum", "qubits", ]
categories  = ["concurrency", "simulation", "mathematics", "science", ]

authors     = ["Denis Drozhzhin <denisdrozhzhin1999@gmail.com>"]
edition     = "2018"
repository  = "https://github.com/MucTepDayH16/qvnt/"
readme      = "README.md"
license-file = "LICENSE.md"

[features]
cpu = ["rayon"]

[dependencies]
lazy_static = { version = "1.4", optional = true }
num-complex = "0.4"
float-cmp   = "0.8"
rand        = "0.8"
rand_distr  = "0.4"
rayon       = { version = "1.5", optional = true }

[dev-dependencies]
criterion   = "0.3"

[[bench]]
name        = "performance"
harness     = false
