name: Criterion

on: [push, pull_request]

env:
  CARGO_TERM_COLOR:
    always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule init && git submodule update
      - name: Benchmark crate
        run: cargo bench --quiet --package qvnt --bench performance --features=cpu