name: Criterion

on: [push, pull_request]

env:
  CARGO_TERM_COLOR:
    always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Benchmark crate
        run: cargo bench --package qvnt --bench performance