name: Criterion

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Benchmark
        run: cargo bench --package qvnt --bench performance