name: Linter

on: [push]

env:
  CARGO_TERM_COLOR:
    always

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set rust channel
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Rustfmt checks
        run: cargo fmt --check

      - name: Clippy checks
        run: cargo clippy --all-targets --all-features -- -Dwarnings

