name: Linter

on: [push]

env:
  CARGO_TERM_COLOR:
    always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set stable channel
        run: rustup default stable

      - name: Add nightly channel
        run: rustup install nightly && rustup +nightly component add rustfmt

      - name: Rustfmt checks
        run: cargo +nightly fmt --check
        
      - name: Clippy checks
        run: cargo clippy --all-targets --all-features -- -Dwarnings

