name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR:
    always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set stable channel
        run: rustup default stable
      - name: Clean space
        run: cargo clean --package qvnt
      - name: Build crate
        run: cargo build --release --package qvnt --features=${{ matrix.features }}
      - name: Test crate
        run: cargo test --quiet --release --package qvnt --features=${{ matrix.features }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        features: [default, cpu]
