name: Rust

on: [push]

env:
  CARGO_TERM_COLOR:
    always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set stable channel
        run: rustup default stable
      - name: Add nightly channel
        run: rustup install nightly
      - name: Rustfmt check
        run: cargo +nightly fmt --check
      - name: Clean space
        run: cargo clean --package qvnt
      - name: Build crate
        run: cargo build --release --package qvnt --all-features
      - name: Test crate
        run: cargo test --quiet --release --package qvnt --all-features
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
