name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/submodules-init@v4
    - name: Build
      run: cargo build --package qvnt --release --verbose
    - name: Run tests
      run: cargo test --package qvnt --release --verbose
